services:
  - type: web
    name: escola-high-tech-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Issuer
        value: escola-api
      - key: Jwt__Audience
        value: escola-client
      - key: Jwt__ExpirationMinutes
        value: "120"
      - key: Jwt__Key
        generateValue: true
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: ServiceBus__ConnectionString
        sync: false
      - key: ServiceBus__QueueName
        value: notificacoes
      - key: ServiceBus__ConsumerEnabled
        value: "true"
